{{- if .Values.createCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialSecretName | quote }}
  labels:
    {{- include "capz.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep # credentials have to be available throughout a delete operation
stringData: # https://azure.github.io/azure-service-operator/guide/authentication/credential-format/
  {{- if .Values.subscriptionID }}
  AZURE_SUBSCRIPTION_ID: {{ .Values.subscriptionID | quote }}
  {{- end }}
  {{- if .Values.tenantID }}
  AZURE_TENANT_ID: {{ .Values.tenantID | quote }}
  {{- end }}
  {{- if .Values.clientID }}
  AZURE_CLIENT_ID: {{ .Values.clientID | quote }}
  {{- end }}
  {{- if .Values.clientSecret }}
  AZURE_CLIENT_SECRET: {{ .Values.clientSecret | quote }}
  {{- end }}
  {{- if .Values.authMode }}
  AUTH_MODE: {{ .Values.authMode | quote }}
  {{- end }}
{{- end }}
